name: Build QModem armsr/armv8 (TarGz Output)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4
        with:
          path: qmodem_src

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libncurses-dev libssl-dev python3-setuptools python3-dev rsync unzip zlib1g-dev file wget curl zstd

      - name: Download and Extract OpenWrt SDK
        run: |
          PAGE_URL="https://downloads.openwrt.org/releases/24.10.5/targets/armsr/armv8/"
          SDK_FILE=$(curl -s $PAGE_URL | grep -oE 'openwrt-sdk-[^"]+armsr-armv8[^"]+\.Linux-x86_64\.tar\.(xz|zst)' | head -n 1)
          wget -O sdk_archive "${PAGE_URL}${SDK_FILE}"
          mkdir sdk_dir
          tar -xf sdk_archive -C sdk_dir --strip-components=1

      - name: Setup Feeds
        working-directory: ./sdk_dir
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # Menggunakan folder lokal hasil checkout sebagai sumber
          echo "src-link qmodem $GITHUB_WORKSPACE/qmodem_src" >> feeds.conf.default
          ./scripts/feeds update qmodem
          ./scripts/feeds install -a -p qmodem

      - name: Compile QModem Packages
        working-directory: ./sdk_dir
        run: |
          make defconfig
          make package/luci-app-qmodem/compile V=s -j$(nproc)
          make package/luci-app-qmodem-sms/compile V=s -j$(nproc)
          make package/luci-app-qmodem-mwan/compile V=s -j$(nproc)
          make package/luci-app-qmodem-ttl/compile V=s -j$(nproc)

      - name: Buat Arsip Tar.gz
        run: |
          # 1. Buat folder sementara untuk menampung semua file .ipk hasil build
          mkdir -p output_folder
          find sdk_dir/bin/packages/ -name "*.ipk" -exec cp {} output_folder/ \;
          
          # 2. Kompres folder tersebut menjadi file .tar.gz
          tar -cvzf qmodem_armsr_armv8.tar.gz -C output_folder .
          
          echo "Arsip berhasil dibuat: qmodem_armsr_armv8.tar.gz"

      - name: Upload ke GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QModem-OpenWrt-24.10.5-Tarball
          # Kita hanya mengunggah SATU file ini saja
          path: qmodem_armsr_armv8.tar.gz
